// <auto-generated />
using System;
using ClinicaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicaAPI.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    [Migration("20201217014935_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ClinicaAPI.Models.Atendimento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("pacienteid");

                    b.Property<string>("prontuario");

                    b.HasKey("id");

                    b.HasIndex("pacienteid");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("documento");

                    b.Property<DateTime>("dt_nascimento");

                    b.Property<string>("nome");

                    b.Property<string>("sexo");

                    b.HasKey("id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaAPI.Models.Atendimento", b =>
                {
                    b.HasOne("ClinicaAPI.Models.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteid");
                });
#pragma warning restore 612, 618
        }
    }
}
